### ISSUE TITLE
Issue running code

### ISSUE THREAD

**Issue by mpierrau** [babaksit/MLOps-bootcamp#1]
Hi, I'm evaluating your project for the course, but I have run in to an issue when trying to run your code - could we connect on slack so that you can help me debug? I'd like to give give your project an honest try, but I'm not too familiar with airflow and kubernetes myself, so I'd appreciate some help!

**Comment by babaksit** [comment]
Hello Magnus,
Thank you for your honest review :) . So I will be heading a vacation this weekend, but I have time today until 3pm, or on Monday if it is not too late. During weekend I can also answer from my cell phone, from time to time maybe also :)
I just created a workspace: https://join.slack.com/t/newworkspace-nkq7330/shared_invite/zt-2p6xgptp1-iheDnOeOwL5WheP18jq4bQ
